name: CI/CD Pipeline

on:
    push: 
        branches: [ main ]

jobs:
    commande-de-base:
        runs-on: ubuntu-latest
    
        steps:
            - name: create folder
              run: mkdir newFolder

    test-job:
        runs-on: ubuntu-latest
        needs: commande-de-base
        steps:
            - name: clone code source
              uses: actions/checkout@v4
            - name: list folders
              run: ls -l

            - name: build docker image
              run: docker build -t html-session9 .